#@ File (label = "Input directory", style = "directory") input
#@ File (label = "Output data table name", style="save") outputFile

/*
Define fluorescent channels to correlate below
These strings should be at the end of all image files, include any prepended delimiters, e.g. '_'
*/
chan1 = "_RFP";
chan2 = "_GFP";

//Ensure correct file extension on output table
if(endsWith(outputFile, ".csv")){
	f = File.open(outputFile);
} else {
	f = File.open(outputFile + ".csv");
}

//header line for eventual table
print(f,"Image Name,# of cells,ROI,Pearson's Coefficient");

//do the thing
processFolder(input);

//takes a directory and recursively searches until all images and ROI sets are found
function processFolder(input){
	flist = getFileList(input);
	flist = Array.sort(flist);

	for (i=0; i < flist.length; i++) {

		// Recursively invokes processFolder() on directories found within the original argument
		// Excludes any "output ROIs" directories generated by previous macro runs
		if(File.isDirectory(input + File.separator + flist[i]) && File.getName(flist[i]) != "output ROIs"){
			flist[i] = flist[i].substring(0, indexOf(flist[i], "/"));
			processFolder(input + File.separator + flist[i]);
		}

		// Looks for RFP images with corresponding ROI sets (manually created prior to processing)
		if(endsWith(flist[i], "_RFP.tif") && File.exists(input + File.separator + "RoiSet.zip")){

			// do-while loop processes the images until a non-zero pearson value is returned, or the image is processed 3 times
			j = 0;
			do {
				j++;
				// Calculates Pearson Coefficient
				processImages(input, flist[i]);
				//saves log as .txt file
				logStr = getInfo("log");
				//Returns 'True' is pearson value is 0
				zeroCheck = logToTable(f, logStr, j);
				if(zeroCheck){
					print("**** CAUTION: Double check the zero value is real ****");
					logStr = getInfo("log");
				}
				File.saveString(logStr, input + File.separator + "procNum" + j + ".txt");
			} while (zeroCheck && j < 3);
		}
	}
}

//generates roi sets and calculates Pearson Coefficient using JaCoP
function processImages(input, file) {
	//Clears log and prints header
	print("\\Clear");
	print("Processing contents of directory: " + input + "\n**************************************************");

	base_img = file.substring(0, lastIndexOf(file, "_"));
	GFP_img = base_img + "_GFP.tif";

	//add this code in if there are issues where the macro can't find files or directories due to trailing file separators
	/*
	if(endsWith(input, File.separator)){
		input = input.substring(0, lastIndexOf(input, File.separator));
	}
	*/

	// Generate 8-bit ROI images for JaCoP input
	open(input + File.separator +file);
	run("8-bit");
	open(input + File.separator + GFP_img);
	run("8-bit");

	run("ROI Manager...");
	open(input + File.separator + "RoiSet.zip");

	outdir = input + File.separator + "output ROIs";
	File.makeDirectory(outdir);

	makeROIs(input, file, "_RFP");
	makeROIs(input, GFP_img, "_GFP");


	//Makes the log file header
	print("Image Name: " + base_img);
	print("# of cells: " + roiManager("count"));

	//Call JaCoP to calculate Pearson Coefficients
	roi_ls = getFileList(outdir);
	for (i = 0; i < roi_ls.length; i+=2) {
		open(outdir + File.separator + roi_ls[i]);
		open(outdir + File.separator + roi_ls[i+1]);
		run("JACoP ", "imga=" + roi_ls[i] + " imgb=" + roi_ls[i+1] +" pearson");
	}

	//Comment this close statement out (add "//" before the line) to prevent the macro from closing all images
	close("*");

	roiManager("reset");

	print("**************************************************\nFinished processing directory");
}

// Generate ROI selecetions from raw images
function makeROIs(input, file, channel){
	for (i = 0; i < roiManager("count"); i++) {
		selectImage(file);
		roiManager("Select", i);
		run("Duplicate...", " ");
		setBackgroundColor(0, 0, 0);
		run("Clear Outside");
		roiName = RoiManager.getName(i);
		coord1 = roiName.substring(0,indexOf(roiName, "-"));
		coord2 = roiName.substring(indexOf(roiName, "-"));
		fname = coord1 + coord2 + channel;
		outfile = input + File.separator + "output ROIs" + File.separator + fname;
		saveAs("Tiff", outfile);
		close();
	}
}


// Appends pearson values written to the log into a CSV
// Also checks for erroneous 0 values output due to race conditions
function logToTable(infile, logStr, loopNum) {

	//format header row
	logArr = split(logStr, "([\*]+\n)");
	firstRow = split(logArr[1],"\n");
	for (i = 0; i < firstRow.length; i++) {
		firstRow[i] = firstRow[i].substring(indexOf(firstRow[i], ":")+2);
	}

	zeroCheck = 0;
	pearsonArr = newArray(2);
	resultStr = "";

	//writes all pearson values for a given image to CSV
	//each ROI is printed to a separate line
	i = 2;
	do {
		pearsonArr[0] = logArr[i].substring(indexOf(logArr[i], ":")+2, indexOf(logArr[i], "_"));
		pearsonArr[1] = logArr[i].substring(indexOf(logArr[i], "=")+1);
		//check for 0 value
		if(String.trim(pearsonArr[1]) == "0.0")
			zeroCheck = 1;
		rowArr = Array.concat(firstRow,pearsonArr);
		resultStr = resultStr + String.join(rowArr);
		//Comment this out if you want the image name and cell count to be repeated on each row
		//Otherwise, image name and cell count will only print with first ROI for the image
		firstRow = newArray("-","-");

		i++;
	} while (i < logArr.length-1);

	//only print a 0 value to the output CSV if it has been checked 3 times
	if (!zeroCheck || loopNum == 3)
		print(infile, resultStr);

	return zeroCheck;
}
